# Forces new Travis-CI Infrastructure
sudo: false

language: php

# list any PHP version you want to test against
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - RUN_UNIT_TESTS="yes"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: 7.1
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    # Requires older Precise image
    - php: 5.3
      env: INSTALL_APC="yes"
      sudo: true
      dist: precise
    # The new Trusty image has issues with running APC, do not enable it here
    - php: 5.4
      env: INSTALL_APC="no"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: INSTALL_APCU="yes"
    - php: 7.2
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: nightly
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
  allow_failures:
    - php: 7.2
    - php: nightly